algoritmo "Loop PARA"
//Ler e exibir o nome e idade de 3 pessoas"
var
  nome: caractere
  idade, contador: inteiro
inicio

  para contador de 1 ate 3 faca
    // ENTRADAS
    escreva("Informe nome: ")
    leia(nome)
    escreva("Informe idade: ")
    leia(idade)

    // SAÍDA
    escreval()  // apenas para pular linha
    escreval("Nome: ",nome, " - Idade: ",idade)
    escreval()  // apenas para pular linha
  fimpara

fimalgoritmo
