algoritmo "EXERCÍCIO 09 - LOOP BANDAS"
// Pedir e exibir 5 bandas
var
   banda: caractere
   contador: inteiro
   
   // Usando variáveis para controle do loop
   //x, y: inteiro
inicio
  //x <- 1
  //y <- 3

  // para contador de x ate y faca
  para contador de 1 ate 3 faca
    // ENTRADA
    escreva("Informe a",contador, "ª banda: ")
    leia(banda)

    // SAÍDA
    escreval("A banda informada foi: ", banda)
    escreval()
  fimpara
fimalgoritmo
